name: CI/CD pipleline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
    - uses: actions/checkout@v4
    - name: Login to Dockerhub
    - uses: docker/login-action@v1
      with: 
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password : ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build, tag, and push image to DockerHub
      env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          IMAGE_NAME: my-image
      run:
           docker build -t DOCKERHUB_USERNAME/$IMAGE_NAME .
           docker push $DOCKERHUB_USERNAME/$IMAGE_NAME:latest
  test:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout code
         uses: action/checkout@v2
       - name: Set up Python
         uses: actions/setup-python@v1
         with:
           python-version: '3.x'
       - name: Install dependencies
         run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
       - name: Test with pytest
         run: |
            pip install pytest
            pytest -v test.py
       
           
